title: 
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 
  <br><br>
  <a href="https://www.linkedin.com/in/indrajitsinghds/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-cayman
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
# basic options
title: Indrajit Singh # your name (or website title) here
author: Indrajit SIngh
email: indrajitsingh37@gmail.com
description: A wonderful site for learning Natural Language Processing and AI
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
